
### Customers ###

// get a list of all customers
GET http://localhost:3000/customers HTTP/1.1

###

// create a customer
POST http://localhost:3000/customers HTTP/1.1
content-type: application/json

{"customerId":5, "customerName": "Yessir Peterson", "basket": []}
###

// get a customer by id
GET http://localhost:3000/customers/30 HTTP/1.1

###

// update a customer by id
PUT  http://localhost:3000/customers/5 HTTP/1.1
content-type: application/json

{"customerId":5, "customerName": "John Johnson UPDATED!"}
###

// delete customer by id
DELETE  http://localhost:3000/customers/5 HTTP/1.1

###


### Basket ###

// get basket for specific costumer id
GET http://localhost:3000/customers/30/basket HTTP/1.1

###

// add product to basket for specific costumer id
POST http://localhost:3000/customers/30/basket HTTP/1.1
content-type: application/json

{"productId":5}

###

// delete product id from basket for specific costumer id
DELETE  http://localhost:3000/customers/30/basket/4 HTTP/1.1

###



