// get all information about all products
GET http://localhost:3000/products HTTP/1.1

###

// get all important product info
GET http://localhost:3000/products/info HTTP/1.1
###

// get product by id
GET http://localhost:3000/products/5 HTTP/1.1

###

// get all product categories
GET http://localhost:3000/product/categories/ HTTP/1.1

###


// get product by category
GET http://localhost:3000/product/categories/tea HTTP/1.1

###
